get_target_property(NLOHMANN_JSON_INCLUDE_DIR nlohmann_json INTERFACE_INCLUDE_DIRECTORIES)
set(NLOHMANN_JSON_HEADERS
    ${NLOHMANN_JSON_INCLUDE_DIR}/nlohmann/json.hpp
    )

install(FILES ${NLOHMANN_JSON_HEADERS} DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/nlohmann)

get_target_property(SIMPLE_WEBSOCKET_SERVER_INCLUDE_DIR simple-websocket-server INTERFACE_INCLUDE_DIRECTORIES)
set(SIMPLE_WEBSOCKET_SERVER_HEADERS
    ${SIMPLE_WEBSOCKET_SERVER_INCLUDE_DIR}/asio_compatibility.hpp
    ${SIMPLE_WEBSOCKET_SERVER_INCLUDE_DIR}/client_ws.hpp
    ${SIMPLE_WEBSOCKET_SERVER_INCLUDE_DIR}/crypto.hpp
    ${SIMPLE_WEBSOCKET_SERVER_INCLUDE_DIR}/mutex.hpp
    ${SIMPLE_WEBSOCKET_SERVER_INCLUDE_DIR}/server_ws.hpp
    ${SIMPLE_WEBSOCKET_SERVER_INCLUDE_DIR}/status_code.hpp
    ${SIMPLE_WEBSOCKET_SERVER_INCLUDE_DIR}/utility.hpp
    )

message(${SIMPLE_WEBSOCKET_SERVER_HEADERS})
install(FILES ${SIMPLE_WEBSOCKET_SERVER_HEADERS} DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/simple-websocket-server)
